// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop_entries} from '../models';

export function FuzzyFindDesktopEntry(arg1:string):Promise<Array<any>>;

export function GetDesktopEntries():Promise<Array<desktop_entries.Entry>>;

export function HideLauncher():Promise<void>;

export function LaunchApp(arg1:string):Promise<void>;
