// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FuzzyFindDesktopEntry(arg1) {
  return window['go']['main']['App']['FuzzyFindDesktopEntry'](arg1);
}

export function GetDesktopEntries() {
  return window['go']['main']['App']['GetDesktopEntries']();
}

export function HideLauncher() {
  return window['go']['main']['App']['HideLauncher']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}
