// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function GetDesktopEntries():Promise<Array<desktop.Entry>>;

export function HideLauncher():Promise<void>;

export function LaunchApp(arg1:string):Promise<void>;
